### ISSUE TITLE
Run Local Node Issue

### ISSUE THREAD

**Issue by jurmb84** [vertcoin/One-Click-Miner#35]
Click Run Local Node... During download it displays:

An issue occurred during the download.  Please try again.

I cannot find a log to see what is going wrong... p2pool directory is created, p2pool.zip is downloaded and extracted... Vertcoin Core is downloaded and sync'd... I don't know where to look to see what the issue is.

Windows 8.1 / NVidia / i7 Extreme

**Comment by jurmb84** [comment]
Found the log... if I delete the p2pool folder and start from scratch, i get:

```
Client_P2PoolDownloadCompleted: System.IO.IOException: The process cannot access the file because it is being used by another process
   at Microsoft.VisualBasic.FileIO.FileSystem.ThrowWinIOError(Int32 errorCode)
   at Microsoft.VisualBasic.FileIO.FileSystem.CopyOrMoveFile(CopyOrMove operation, String sourceFileName, String destinationFileName, Boolean overwrite, UIOptionInternal showUI, UICancelOption onUserCancel)
   at VertcoinOneClickMiner.Main.Client_P2PoolDownloadCompleted(Object sender, AsyncCompletedEventArgs e)
```

When i try again without deleting the p2pool folder I get:

```
Client_P2PoolDownloadCompleted: System.IO.IOException: The file 'C:\Users\xxx\Documents\Vertcoin One-Click Miner\p2pool\p2pool-vtc\Start P2Pool Network 2.bat' already exists.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry source, String destinationFileName, Boolean overwrite)
   at System.IO.Compression.ZipFileExtensions.ExtractToDirectory(ZipArchive source, String destinationDirectoryName)
   at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName, Encoding entryNameEncoding)
   at VertcoinOneClickMiner.Main.Client_P2PoolDownloadCompleted(Object sender, AsyncCompletedEventArgs e)
```

Even after deleting all of the files in that directory and trying again, it still gives the same error...

**Comment by zemrys** [comment]
Update your OCM to the newest version found [HERE](https://github.com/vertcoin/One-Click-Miner/releases).  Also, be sure you security software (virus scanner/firewalls, etc.) is not preventing the OCM from running or accessing directories.
