### ISSUE TITLE
Run Local Node closes immediately

### ISSUE THREAD

**Issue by tylertylerday** [vertcoin/One-Click-Miner#64]
After updating to the latest version, when i check "run local node" - the window opens but closes immediately after.

**Comment by KJee85** [comment]
I just ran into this after updating as well. Seems that there are certain cases where p2pool either fails to update or does not prompt to update. This then makes the new '--address-share-rate'  option for p2pool invalid and so it closes immediately.

The way I got around this was to Documents\Vertcoin One-Click Miner which is the default location for p2pool and the other relevant programs/config, rename the p2pool folder to something like p2pool.bk then launch it again, this time it will prompt to update and install the latest version.

**Comment by tylertylerday** [comment]
Thanks @KJee85 that worked for updating. But now i'm getting this error.

```
2018-01-13 10:26:13.691000 p2pool (version 3d0f826-dirty)
2018-01-13 10:26:13.692000
2018-01-13 10:26:13.692000 Testing bitcoind RPC connection to 'http://127.0.0.1:5888/' with username 'iHAOHYjiivxNUCjEXpAXQH21Y'...
Error while checking Bitcoin connection:
Traceback (most recent call last):
  File "twisted\internet\defer.pyc", line 653, in _runCallbacks

  File "twisted\internet\defer.pyc", line 1357, in gotResult

  File "twisted\internet\defer.pyc", line 1299, in _inlineCallbacks

  File "twisted\python\failure.pyc", line 393, in throwExceptionIntoGenerator

--- <exception caught here> ---
  File "p2pool\util\deferral.pyc", line 41, in f

  File "twisted\internet\defer.pyc", line 1299, in _inlineCallbacks

  File "twisted\python\failure.pyc", line 393, in throwExceptionIntoGenerator

  File "p2pool\bitcoin\helper.pyc", line 17, in check

  File "twisted\internet\defer.pyc", line 1299, in _inlineCallbacks

  File "twisted\python\failure.pyc", line 393, in throwExceptionIntoGenerator

  File "p2pool\util\jsonrpc.pyc", line 126, in _http_do

twisted.web.error.Error: 401 Unauthorized
```

**Comment by tylertylerday** [comment]
I have vertcoin core running and updated.

**Comment by KJee85** [comment]
@tylertylerday trying to remember when I encountered that as well. I think I just restarted everything and it worked, you can double check your vertcoin.conf and ensure it does match what it's trying to use there. You could also try just letting it recreate it as well.

My main concern right now is after updating I have not seen a payout on my local node. My time to share jumped way up and I have no estimated payout. Mined all of last night and most of today with nothing where before I updated I was seeing payouts sometimes twice an hour. Might just be p2pool...

**Comment by zemrys** [comment]
@tylertylerday You updated your core wallet to 0.12?  Also be sure to restart your wallet when prompted by the OCM.
