### ISSUE TITLE
OCM - P2pool Issues

### ISSUE THREAD

**Issue by aaronckj** [vertcoin/One-Click-Miner#68]
Today after updating my node I cannot connect to it with any of my miners.  Below is a snapshot of the CLI window upon node startup.  

I deleted the OCM settings folder in the documents directory and I get this.  Node will not start.

2018-01-14 23:36:52.277000 p2pool (version 3d0f826-dirty)
2018-01-14 23:36:52.277000
2018-01-14 23:36:52.278000 Testing bitcoind RPC connection to 'http://127.0.0.1:5888/' with username 's6Dsa4yuHKC7GduMbfOhR7Lg8'...
2018-01-14 23:36:52.296000     ...success!
2018-01-14 23:36:52.297000     Current block hash: 421fc0520d96cd5aa223cfd20b694eacce9f48c1929249389ba313fd5c2b64ca
2018-01-14 23:36:52.297000     Current block height: 859526
2018-01-14 23:36:52.297000
2018-01-14 23:36:52.297000 Testing bitcoind P2P connection to '127.0.0.1:5889'...
2018-01-14 23:36:52.301000     ...success!
2018-01-14 23:36:52.301000
2018-01-14 23:36:52.301000 Determining payout address...
2018-01-14 23:36:52.301000     ...success! Payout address: VpBsRnN749jYHE9hT8dZreznHfmFMdE1yG
2018-01-14 23:36:52.302000
2018-01-14 23:36:52.302000 Loading shares...
2018-01-14 23:36:52.302000     ...done loading 0 shares (0 verified)!
2018-01-14 23:36:52.302000
2018-01-14 23:36:52.303000 Initializing work...
2018-01-14 23:36:52.329000     ...success!
2018-01-14 23:36:52.330000
2018-01-14 23:36:52.330000 Joining p2pool network using port 9346...
2018-01-14 23:36:52.349000     ...success!
2018-01-14 23:36:52.350000
2018-01-14 23:36:52.350000 Listening for workers on '' port 9171...
2018-01-14 23:36:52.397000     ...success!
2018-01-14 23:36:52.520000
2018-01-14 23:36:52.521000 Started successfully!
2018-01-14 23:36:52.521000 Go to http://127.0.0.1:9171/ to view graphs and statistics!
2018-01-14 23:36:52.521000 Donating 1.0% of work towards Vertcoin's development. Thank you!
2018-01-14 23:36:52.521000 You can increase this amount with --give-author argument! (or decrease it, if you must)
2018-01-14 23:36:52.521000
2018-01-14 23:36:52.699000 Outgoing connection to peer 158.69.204.117:9346 established. p2pool version: 1700 'a61a40f-dirty'
2018-01-14 23:36:52.783000 Peer sent entire transaction 05ce88a16eaaa5488dfb0e010b02d446f36bc6cb97c541e9e8d8e2b1f0583684 that was already received
Error in DeferredResource handler:
Traceback (most recent call last):
  File "p2pool\util\deferred_resource.pyc", line 24, in render

  File "twisted\internet\defer.pyc", line 150, in maybeDeferred

  File "twisted\web\resource.pyc", line 250, in render

  File "twisted\internet\defer.pyc", line 1447, in unwindGenerator

--- <exception caught here> ---
  File "twisted\internet\defer.pyc", line 1301, in _inlineCallbacks

  File "p2pool\web.pyc", line 198, in render_GET

  File "p2pool\web.pyc", line 203, in <lambda>

  File "p2pool\data.pyc", line 630, in get_pool_attempts_per_second

exceptions.AssertionError:

Error in DeferredResource handler:
Traceback (most recent call last):
  File "p2pool\util\deferred_resource.pyc", line 24, in render

  File "twisted\internet\defer.pyc", line 150, in maybeDeferred

  File "twisted\web\resource.pyc", line 250, in render

  File "twisted\internet\defer.pyc", line 1447, in unwindGenerator

--- <exception caught here> ---
  File "twisted\internet\defer.pyc", line 1301, in _inlineCallbacks

  File "p2pool\web.pyc", line 198, in render_GET

  File "p2pool\web.pyc", line 203, in <lambda>

  File "p2pool\data.pyc", line 630, in get_pool_attempts_per_second

exceptions.AssertionError:

2018-01-14 23:36:54.229000 Requesting parent share 493592ab from 158.69.204.117:9346
Error in DeferredResource handler:
Traceback (most recent call last):
  File "p2pool\util\deferred_resource.pyc", line 24, in render

  File "twisted\internet\defer.pyc", line 150, in maybeDeferred

  File "twisted\web\resource.pyc", line 250, in render

  File "twisted\internet\defer.pyc", line 1447, in unwindGenerator

--- <exception caught here> ---
  File "twisted\internet\defer.pyc", line 1301, in _inlineCallbacks

  File "p2pool\web.pyc", line 198, in render_GET

  File "p2pool\web.pyc", line 203, in <lambda>

  File "p2pool\data.pyc", line 630, in get_pool_attempts_per_second

exceptions.AssertionError:

2018-01-14 23:36:55.523000 P2Pool: 0 shares in chain (0 verified/1 total) Peers: 1 (0 incoming)
2018-01-14 23:36:55.524000  Local: 0H/s in last 0.0 seconds Local dead on arrival: ??? Expected time to share: ???
Error in DeferredResource handler:
Traceback (most recent call last):
  File "p2pool\util\deferred_resource.pyc", line 24, in render

  File "twisted\internet\defer.pyc", line 150, in maybeDeferred

  File "twisted\web\resource.pyc", line 250, in render

  File "twisted\internet\defer.pyc", line 1447, in unwindGenerator

--- <exception caught here> ---
  File "twisted\internet\defer.pyc", line 1301, in _inlineCallbacks

  File "p2pool\web.pyc", line 198, in render_GET

  File "p2pool\web.pyc", line 203, in <lambda>

  File "p2pool\data.pyc", line 630, in get_pool_attempts_per_second

exceptions.AssertionError:

2018-01-14 23:37:04.565000 Handshake timed out, disconnecting from 94.242.222.27:9346
2018-01-14 23:37:09.232000 Share request timed out!
2018-01-14 23:37:09.233000 Requesting parent share 493592ab from 158.69.204.117:9346
2018-01-14 23:37:09.238000 Lost peer 158.69.204.117:9346 - Connection was aborted locally, using.
in download_shares:
Traceback (most recent call last):
Failure: twisted.internet.error.ConnectionAborted: Connection was aborted locally, using.

2018-01-14 23:37:12.134000 P2Pool: 0 shares in chain (0 verified/1 total) Peers: 0 (0 incoming)
2018-01-14 23:37:12.134000  Local: 0H/s in last 0.0 seconds Local dead on arrival: ??? Expected time to share: ???
2018-01-14 23:37:27.146000 P2Pool: 0 shares in chain (0 verified/1 total) Peers: 0 (0 incoming)
2018-01-14 23:37:27.147000  Local: 0H/s in last 0.0 seconds Local dead on arrival: ??? Expected time to share: ???
Error getting work from bitcoind:
Traceback (most recent call last):
Failure: twisted.internet.error.TimeoutError: User timeout caused connection failure.

2018-01-14 23:37:42.151000 P2Pool: 0 shares in chain (0 verified/1 total) Peers: 0 (0 incoming)
2018-01-14 23:37:42.151000  Local: 0H/s in last 0.0 seconds Local dead on arrival: ??? Expected time to share: ???

**Comment by zemrys** [comment]
The assertion errors you are seeing are common when p2pool is loading/catching up on the share chain.  They will disappear on their own once your node is caught up with the rest of the network.

**Comment by aaronckj** [comment]
The node started working again 2 hrs ago.  It is now down again.  This is the OCM CLI output.

I've restarted my computer, reinstalled both OCM & Core, and deleted the settings in the documents directory.  Any other suggestions?

2018-01-15 15:01:01.787000  Pool: 98757MH/s Stale rate: 13.0% Expected time to block: 21.2 minutes
2018-01-15 15:01:02.620000 Share request timed out!
2018-01-15 15:01:02.620000 Requesting parent share 44ac568c from 82.200.205.30:9346
2018-01-15 15:01:02.620000 Lost peer 82.200.205.30:9346 - Connection was aborted locally, using.
in download_shares:
Traceback (most recent call last):
Failure: twisted.internet.error.ConnectionAborted: Connection was aborted locally, using.

2018-01-15 15:01:04.788000 P2Pool: 17498 shares in chain (12125 verified/17503 total) Peers: 0 (0 incoming)
2018-01-15 15:01:04.788000  Local: 0H/s in last 0.0 seconds Local dead on arrival: ??? Expected time to share: ???
2018-01-15 15:01:04.788000  Shares: 0 (0 orphan, 0 dead) Stale rate: ??? Efficiency: ??? Current payout: (0.0000)=0.0000 VTC
2018-01-15 15:01:04.788000  Pool: 98757MH/s Stale rate: 13.0% Expected time to block: 21.2 minutes
2Unhandled error in Deferred:


Error when requesting noncached value:


Error when requesting noncached value:


Error when requesting noncached value:


Error when requesting noncached value:


Error when requesting noncached value:


Error when requesting noncached value:


Error when requesting noncached value:


Error when requesting noncached value:


Error when requesting noncached value:


Error when requesting noncached value:


Error when requesting noncached value:


Error when requesting noncached value:


Error when requesting noncached value:

**Comment by aaronckj** [comment]
@zemrys 

I also get this.  

2018-01-15 15:08:45.070000 > >>> Warning: LOST CONTACT WITH BITCOIND for 1.0 minutes! Check that it isn't frozen or dead!
2018-01-15 15:08:45.070000 > ########################################
2018-01-15 15:08:48.084000 > ########################################
2018-01-15 15:08:48.084000 > >>> Warning: LOST CONTACT WITH BITCOIND for 1.1 minutes! Check that it isn't frozen or dead!
2018-01-15 15:08:48.084000 > ########################################

**Comment by arruah** [comment]
> The node started working again 2 hrs ago. It is now down again. This is the OCM CLI output.
> 
> I've restarted my computer, reinstalled both OCM & Core, and deleted the settings in the documents directory. Any other suggestions?
> 
> 2018-01-15 15:01:01.787000 Pool: 98757MH/s Stale rate: 13.0% Expected time to block: 21.2 minutes
> 2018-01-15 15:01:02.620000 Share request timed out!
> 2018-01-15 15:01:02.620000 Requesting parent share 44ac568c from 82.200.205.30:9346
> 2018-01-15 15:01:02.620000 Lost peer 82.200.205.30:9346 - Connection was aborted locally, using.
> in download_shares:
> Traceback (most recent call last):
> Failure: twisted.internet.error.ConnectionAborted: Connection was aborted locally, using.
> 
> 2018-01-15 15:01:04.788000 P2Pool: 17498 shares in chain (12125 verified/17503 total) Peers: 0 (0 incoming)
> 2018-01-15 15:01:04.788000 Local: 0H/s in last 0.0 seconds Local dead on arrival: ??? Expected time to share: ???
> 2018-01-15 15:01:04.788000 Shares: 0 (0 orphan, 0 dead) Stale rate: ??? Efficiency: ??? Current payout: (0.0000)=0.0000 VTC
> 2018-01-15 15:01:04.788000 Pool: 98757MH/s Stale rate: 13.0% Expected time to block: 21.2 minutes
> 2Unhandled error in Deferred:
> 
> Error when requesting noncached value:
> 
> Error when requesting noncached value:
> 
> Error when requesting noncached value:
> 
> Error when requesting noncached value:
> 
> Error when requesting noncached value:
> 
> Error when requesting noncached value:
> 
> Error when requesting noncached value:
> 
> Error when requesting noncached value:
> 
> Error when requesting noncached value:
> 
> Error when requesting noncached value:
> 
> Error when requesting noncached value:
> 
> Error when requesting noncached value:
> 
> Error when requesting noncached value:

Did you solve this?
