### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by bahadirekici** [vertcoin/One-Click-Miner#76]
Version 1.1.7.9
----------------

I downloaded and installed application.
Select find p2pool Nodes set it up normally.
When i decided to click again p2pool Nodes window and select another pool and click "Close" button its gives an error :

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   **at VertcoinOneClickMiner.P2Pool.PictureBox15_Click**(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by ghost** [comment]
@junas thanks for the input, buddy! I haven't been able to replicate this issue on my end. Try using version 1.1.7.8 for the time being as we're working on a new merge :)
