### ISSUE TITLE
AMD-sgminer download issue

### ISSUE THREAD

**Issue by Agbp12** [vertcoin/One-Click-Miner#83]
After installing the OCM and then choosing a pool , setting to amd-sgminer, and then choosing start the miner, it prompts that there is a download for the AMD-sgminer and do you want to update.  It then gives an error that it encountered an error and appears to start the download manager, but fails: 

- 2018-02-25T05:14:13.7791962Z, LoadSettingsJSON: LoadSettings: OK.
- 2018-02-25T05:14:13.8260726Z, Form1_Load: Loaded: OK, V:1.1.7.9
- 2018-02-25T05:14:17.4042001Z, SaveSettingsJSON: SaveSettings: OK.
- 2018-02-25T05:15:42.0907106Z, Download_Miner: Downloaded OK.
- 2018-02-25T05:15:45.3522859Z, Client_MinerDownloadCompleted: System.IO.InvalidDataException: Central Directory corrupt. ---> System.IO.IOException: An attempt was made to move the file pointer before the beginning of the file.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.SeekCore(Int64 offset, SeekOrigin origin)
   at System.IO.FileStream.Seek(Int64 offset, SeekOrigin origin)
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   --- End of inner exception stack trace ---
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at VertcoinOneClickMiner.Main.Client_MinerDownloadCompleted(Object sender, AsyncCompletedEventArgs e)
- 2018-02-25T05:15:45.3522859Z, SaveSettingsJSON: SaveSettings: OK.
- 2018-02-25T05:15:45.3522859Z, Client_MinerDownloadCompleted: MinerDownloadCompleted: OK.
- 2018-02-25T05:15:54.5241715Z, SystemLogToolStripMenuItem_Click: SystemLogToolStripMenuItem(), Load Miner Log: OK
- 2018-02-25T05:20:18.5869482Z, SystemLogToolStripMenuItem_Click: SystemLogToolStripMenuItem(), Load Miner Log: OK

Windows 10 HomeEdition

**Comment by zemrys** [comment]
Please try the most recent update found [HERE](https://github.com/vertcoin-project/One-Click-Miner/releases/tag/1.1.8.0). This includes a fix for the issues mentioned.  GitHub implemented new security measures recently that broke the OCM's download functionality.
