### ISSUE TITLE
Update downloads failing

### ISSUE THREAD

**Issue by Purgitoria** [vertcoin/One-Click-Miner#85]
I initially installed OCM and it ran fine and installed the update for the Nvidia ccminer but now any other update just fails and it does not seem to be any issue with firewall or antivirus as far as i can see and i even tried adding exceptions and have also tried a repair of the program but still get no downloads happening/completing. The Log entry for the failure is as follows:

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.SeekCore(Int64 offset, SeekOrigin origin)
   at System.IO.FileStream.Seek(Int64 offset, SeekOrigin origin)
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   --- End of inner exception stack trace ---
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at VertcoinOneClickMiner.Main.Client_MinerDownloadCompleted(Object sender, AsyncCompletedEventArgs e)
- 2018-02-26T16:37:50.1549658Z, SaveSettingsJSON: SaveSettings: OK.
- 2018-02-26T16:37:50.1549658Z, Client_MinerDownloadCompleted: MinerDownloadCompleted: OK.
- 2018-02-26T16:37:52.1201921Z, SaveSettingsJSON: SaveSettings: OK.
- 2018-02-26T16:37:55.1302367Z, Kill_P2Pool: Kill_P2Pool: OK.
- 2018-02-26T16:38:02.3234535Z, Download_P2Pool: Downloaded OK.
- 2018-02-26T16:38:04.9063211Z, Client_P2PoolDownloadCompleted: System.IO.InvalidDataException: Central Directory corrupt. ---> System.IO.IOException: An attempt was made to move the file pointer before the beginning of the file.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.SeekCore(Int64 offset, SeekOrigin origin)
   at System.IO.FileStream.Seek(Int64 offset, SeekOrigin origin)
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   --- End of inner exception stack trace ---
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName, Encoding entryNameEncoding)
   at VertcoinOneClickMiner.Main.Client_P2PoolDownloadCompleted(Object sender, AsyncCompletedEventArgs e)
- 2018-02-26T16:38:04.9063211Z, SaveSettingsJSON: SaveSettings: OK.
- 2018-02-26T16:38:04.9073240Z, Client_P2PoolDownloadCompleted: P2PoolDownloadCompleted: OK.
- 2018-02-26T16:38:38.5257167Z, SystemLogToolStripMenuItem_Click: SystemLogToolStripMenuItem(), Load Miner Log: OK
- 2018-02-26T16:39:40.4862853Z, SaveSettingsJSON: SaveSettings: OK.
- 2018-02-26T16:39:42.6340223Z, Kill_P2Pool: Kill_P2Pool: OK.
- 2018-02-26T16:39:50.6139368Z, Download_P2Pool: Downloaded OK.
- 2018-02-26T16:39:53.3602396Z, Client_P2PoolDownloadCompleted: System.IO.InvalidDataException: Central Directory corrupt. ---> System.IO.IOException: An attempt was made to move the file pointer before the beginning of the file.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.SeekCore(Int64 offset, SeekOrigin origin)
   at System.IO.FileStream.Seek(Int64 offset, SeekOrigin origin)
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   --- End of inner exception stack trace ---
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName, Encoding entryNameEncoding)
   at VertcoinOneClickMiner.Main.Client_P2PoolDownloadCompleted(Object sender, AsyncCompletedEventArgs e)
- 2018-02-26T16:39:53.3612421Z, SaveSettingsJSON: SaveSettings: OK.
- 2018-02-26T16:39:53.3612421Z, Client_P2PoolDownloadCompleted: P2PoolDownloadCompleted: OK.
- 2018-02-26T16:39:54.8672469Z, SaveSettingsJSON: SaveSettings: OK.
- 2018-02-26T16:45:54.6643939Z, SystemLogToolStripMenuItem_Click: SystemLogToolStripMenuItem(), Load Miner Log: OK

**Comment by zemrys** [comment]
[Issue 84](https://github.com/vertcoin-project/One-Click-Miner/issues/84)

**Comment by Purgitoria** [comment]
As i mentioned in my post i have already been through the exceptions and firewall rules which allow the program to operate but still have issue. Normally if a program is blocked then KAV will push a notification that it had blocked a program and there would be evidence of it in the log. The thread which you reference in your link of the other post seems to deal with issues of actually downloading and installing the base program and not the addons/plugins that the program wants to install when it is up and running. Perhaps i am missing something?

**Comment by zemrys** [comment]
If your miner updates are actively failing, you have something preventing them from being downloaded/extracted.  Try turning off your security software entirely temporarily to see if that fixes the issue.

**Comment by Purgitoria** [comment]
I did try that as well and it makes no  difference. The Log would seem to indicate that the download occurs but there is a problem extracting the file perhaps, though my programming skills are quite basic so i could be wrong. From what i understand of the error log the program is trying to access the download iummediatley once it is complete but before windows has time to make it a valid and user readable one?

**Comment by Purgitoria** [comment]
Is there a repository where i can manually download and extract the required files to the correct folder? That way i should be able to edit the JSON with the correct version ant hopefully all would work?

**Comment by Purgitoria** [comment]
I had a look through the code and the repositories are all working and i can access all of the links if i download manually but of course extracting them correctly is a bit of a different matter and it also requires the downloading and installing of the UI in the process and creation of the config files. To me when i see the process flow i wonder if it does not need to complete the download first before trying to rename it or perhaps there needs to be some kind of delay? I'm no expert in VB so i could well be wrong.

**Comment by Trick17** [comment]
I am having a similar issue.  I have gone to the extent of completely turning off my bitdefender as well as any protection built into windows, but am still having the error.

**Comment by Purgitoria** [comment]
No one seems to have any answers for this issue but for the p2pool you can roughly follow the guide here to manually set up your own p2pool node https://www.youtube.com/watch?v=CE9kGh-gGnI 
Just a couple of points on doing so as i just spent the entire night trying to do it!

- Use only version 2.7.0 of python and make sure it is along with all the other downloads you grab are the 32 bit versions otherwise it will not work. There is a point where there is only a 32 bit version of the WHL wrapper and it will not install unless all the other parts are 32 bit.

- As this guide is a bit older then you will already get 2 batch files, one for network 1 and 2. What it does not tell you however is that you must ass some extra code in there to get it to work with the vertcoin.conf that you created. The total edit should look something like this : 

run_p2pool.exe --net vertcoin -f 0.1 --give-author 0 rcpuser rcppassword --max-conns 10000           
pause

where rcpuser and rcppassword should be replaced with the values you set in vertcoin.conf and don't forget to restart the core after you set or change the values in the .conf or it will not work.

You can also go to the following link https://github.com/justino/p2pool-ui-punchy/releases to download the current version of the custon UI that OCM would have used anyway which you can extract, rename the folder to web-static and replace the web-static folder where you dropped your p2pool folder with this one which will give you some nice options for changing the look of your UI.

**Comment by zemrys** [comment]
Please try the most recent update found [HERE](https://github.com/vertcoin-project/One-Click-Miner/releases/tag/1.1.8.0). This includes a fix for the issues mentioned.  GitHub implemented new security measures recently that broke the OCM's download functionality.

**Comment by Purgitoria** [comment]
Thanks. That has now resolved the issues.
